### ISSUE TITLE
[Epic] Implement Vincent Galley's asking

### ISSUE THREAD

**Issue by proteusvi** [republique-et-canton-de-geneve/noms-geographiques#14]
# Definition :
In the search page, review the representation of dates on the search page.

# Tasks :
- [x] Place the two dates into one line.
- [] Move the dates line at the end of the facets before the button.
- [ ] Repare bug already present into the actual version deployed @see [PHP-835](https://prod.etat-ge.ch/csbugtrack/browse/PHP-835).
